language: python
python:
    - "2.6"
# command to install dependencies
install:
      - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
        - "pylint --version"
        - "PYTHONPATH=./snapwatchd:./drivers pylint --rcfile=tests/pylintrc ./drivers/*.py"
        - "cd drivers; nosetests --with-coverage -c ../.noserc ../tests/test_*.py"
after_success:
        coveralls
