#!/usr/bin/bash
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU Lesser General Public License as published 
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# on-master-start script to adjust VHD-cleanup setup when master changes

# Source function library.
. /etc/init.d/functions

CLEANUP_SCRIPT="/opt/xensource/sm/cleanup.py"
LVHD_UTIL_SCRIPT="/opt/xensource/sm/lvhdutil.py"

start() {
    echo -n $"Fixing refcounts on new master: "
    logger -p local2.info "Fixing refcounts on new master: "

    for type in lvhdoiscsi lvhdohba lvhdofcoe lvmoiscsi lvmohba lvmofcoe; do
        srUuids=`xe sr-list type=$type params=uuid --minimal | sed "s/,/ /g"`
        for uuid in $srUuids; do
            echo -n "Fixing $type"
            python $LVHD_UTIL_SCRIPT fixrefcounts $uuid
        done
    done
	echo -n $"OK"
	success $"OK"
	echo
	return 0
}

stop() {
    echo -n $"Aborting running cleaners: "
    logger -p local2.info "Aborting running cleaners: "
    TYPES=`xe sm-list required-api-version=1.0 params=type --minimal | tr ',' '\n'`
    for type in $TYPES; do
        srUuids=`xe sr-list type=$type params=uuid --minimal | sed "s/,/ /g"`
        for uuid in $srUuids; do
            $CLEANUP_SCRIPT -u $uuid -a
        done
    done
	echo -n $"OK"
	success $"OK"
	echo
	return 0
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac
