#!/usr/bin/python3
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# LVHDoISCSISR: LVHD over ISCSI software initiator SR driver
#               matches with libs/sm/drivers/LVHDoISCSISR.py
#
# Note: This is a copy of LVHDoISCSISR because the LVHDoISCSISR module behaves differently
# when invoked from a differing command line. This needs fixing to use proper
# subclass behaviour in a future update
#
from sm import SRCommand
from sm.drivers.LVHDoISCSISR import LVHDoISCSISR, DRIVER_INFO

if __name__ == '__main__':
    SRCommand.run(LVHDoISCSISR, DRIVER_INFO)
