#!/usr/bin/python3

# Copyright (C) Cloud Software Group, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""
Health check for SR, to be triggered periodically by a systemd timer. What is checked is
SR implementation type dependent.
"""
# This path adjustment can be removed eventually
import sys
sys.path.append("/opt/xensource/sm/")

from sm import sr_health_check

if __name__ == "__main__":
    sr_health_check.main()
