#!/usr/bin/python3
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# udevSR: represents VDIs which are hotplugged into dom0 via udev e.g.
#         USB CDROM/disk devices
#         matches with libs/sm/drivers/udevSR.py
from sm import SRCommand
from sm.drivers.udevSR import udevSR, DRIVER_INFO

if __name__ == '__main__':
    SRCommand.run(udevSR, DRIVER_INFO)
