#!/usr/bin/python3
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
import sys
from sm import lvhdutil
from sm.lvmcache import LVMCache
from sm.core import util

if __name__ == "__main__":
    # used by the master changeover script
    cmd = sys.argv[1]
    if cmd == "fixrefcounts":
        srUuid = sys.argv[2]
        try:
            vgName = lvhdutil.VG_PREFIX + srUuid
            lvmCache = LVMCache(vgName)
            lvhdutil.setInnerNodeRefcounts(lvmCache, srUuid)
        except:
            util.logException("setInnerNodeRefcounts")
    else:
        util.SMlog("Invalid usage")
        print("Usage: %s fixrefcounts <sr_uuid>" % sys.argv[0])
