#!/bin/sh
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# Kicks a pipe identified by the first argument.
# NOTE: It is not an error for the pipe not to exist, and it will not
# be created in that case.

if [ -z "$1" ]; then
    echo "Syntax: $0 <name>"
    exit 1
fi
dd if=/dev/zero of=/run/$1.sock bs=8 count=1 status=none conv=notrunc,noerror,nocreat oflag=nonblock
