#!/usr/bin/bash

/usr/bin/systemctl list-units SMGC@* --all --no-legend | /usr/bin/awk '{print $1}' | sed 's/\\/\\\\/g' | while read service;
do
    echo "Stopping $service"
    /usr/bin/systemctl stop "$service"
done
