#!/bin/bash

/usr/bin/systemctl list-units SMGC@* --all --no-legend | /usr/bin/cut -d ' ' -f1 | sed 's/\\/\\\\/g' | while read service;
do
    echo "Stopping $service"
    /usr/bin/systemctl stop "$service"
done
