#!/bin/sh
#
# Copyright (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU Lesser General Public License as published 
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# called by UDEV rule to trigger pusb scan, when USB device change is detected

# To prevent the inner scripts calling xe command before xapi is ready, there is
# to add wait for xapi is ready. However the wait may further case usdev to hang
# for long, so here using atd to do the job to make itis detached from udev daemon.
echo "/opt/xensource/libexec/usb_change" | at now

